### ISSUE TITLE
client "Internal server error" with farmer ring from gobber2

### ISSUE THREAD

**Issue by NullExistence1994** [paulevsGitch/EdenRing#35] opened 2022-06-18 17:19 UTC
Failed to handle packet net.minecraft.class_2885@2b41b49, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10074()" because "center" is null
	at paulevs.edenring.world.features.trees.OldBalloonMushroomTreeFeature.method_13151(OldBalloonMushroomTreeFeature.java:37) ~[eden-ring-0.6.1.jar:?]
	at paulevs.edenring.blocks.BalloonMushroomSmallBlock.method_10507(BalloonMushroomSmallBlock.java:53) ~[eden-ring-0.6.1.jar:?]
	at net.minecraft.class_2473.method_9652(class_2473.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_1752.method_7720(class_1752.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_1752.method_7884(class_1752.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:264) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:358) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1115) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Failed to handle packet for /120.15.2.144:58969
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:549) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:241) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:246) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:182) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10074()" because "center" is null
	at paulevs.edenring.world.features.trees.OldBalloonMushroomTreeFeature.method_13151(OldBalloonMushroomTreeFeature.java:37) ~[eden-ring-0.6.1.jar:?]
	at paulevs.edenring.blocks.BalloonMushroomSmallBlock.method_10507(BalloonMushroomSmallBlock.java:53) ~[eden-ring-0.6.1.jar:?]
	at net.minecraft.class_2473.method_9652(class_2473.java:64) ~[server-intermediary.jar:?]
	at com.kwpugh.gobber2.util.GrowingUtil.growCrops(GrowingUtil.java:43) ~[Gobber2-Fabric-1.19.0-2.6.16.jar:?]
	at com.kwpugh.gobber2.items.rings.RingFarmer.method_7888(RingFarmer.java:41) ~[Gobber2-Fabric-1.19.0-2.6.16.jar:?]
	at net.minecraft.class_1799.method_7917(class_1799.java:542) ~[server-intermediary.jar:?]
	at net.minecraft.class_1661.method_7381(class_1661.java:255) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:566) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2384) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:485) ~[server-intermediary.jar:?]
	... 9 more

**Comment by paulevsGitch** [comment] 2022-06-18 17:31
What version are you using? Can please you provide full logs?

**Comment by NullExistence1994** [comment] 2022-06-18 17:36
sry forget that  
[2022-06-19-1.log](https://github.com/paulevsGitch/EdenRing/files/8934061/2022-06-19-1.log)
minecraft 1.19
bclib-2.0.4.jar
edenring 0.6.1
fabricapi 0.55.3
fabricloader 0.14.7

> What version are you using? Can please you provide full logs?

**Comment by paulevsGitch** [comment] 2022-06-18 18:39
Looks like the problem is related to packets:
> Failed to handle packet for


Your packets missing feature-required data (in this case featurePlaceContext.origin()) - block for feature placement that should be always not null:
> NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10074()" because "center" is null


And the final crash is also related to packet, but different:
> Caused by: cn.evolvefield.mods.botapi.util.websocket.exceptions.WebsocketNotConnectedException


I will test this, but I didn't see such errors before, probably something is blocking correct packets on your server or client

**Comment by NullExistence1994** [comment] 2022-06-18 18:49
> Looks like the problem is related to packets:
> 
> > Failed to handle packet for
> 
> Your packets missing feature-required data (in this case featurePlaceContext.origin()) - block for feature placement that should be always not null:
> 
> > NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10074()" because "center" is null
> 
> And the final crash is also related to packet, but different:
> 
> > Caused by: cn.evolvefield.mods.botapi.util.websocket.exceptions.WebsocketNotConnectedException
> 
> I will test this, but I didn't see such errors before, probably something is blocking correct packets on your server or client

thank you I tried to delete the other mods and reproduce the process.

**Comment by NullExistence1994** [comment] 2022-06-18 19:13
[latest.log](https://github.com/paulevsGitch/EdenRing/files/8934171/latest.log) server-side log
Reproduced 
The same mod is used on the server and the client

**Comment by kwpugh** [comment] 2022-06-20 14:41
Hi, I'm the Gobber author.  

My Ring of the Farmer item seems to crash on line 43 during the grow method.

https://github.com/kwpugh/gobber_fabric-1.17/blob/1.19.0/src/main/java/com/kwpugh/gobber2/util/GrowingUtil.java

No idea why.

**Comment by paulevsGitch** [comment] 2022-06-21 12:57
I found a bug, one of methods didn't react on null properly, next version will fix it

**Comment by kwpugh** [comment] 2022-06-21 13:11
Wonderful, thank you for tracking that down.

**Comment by paulevsGitch** [comment] 2022-06-22 06:31
Should be fixed in 0.6.2

**Closed by paulevsGitch** 2022-06-22 06:31 UTC
Labels: bug
