### ISSUE TITLE
Crash when entering the dimension.

### ISSUE THREAD

**Issue by DaenenTDD** [paulevsGitch/EdenRing#47] opened 2022-08-13 05:42 UTC
The server crashes when I enter the dimension. This appears to be a new problem as it wasn't happening yesterday.
[crash-2022-08-13_05.39.32-server.txt](https://github.com/paulevsGitch/EdenRing/files/9330900/crash-2022-08-13_05.39.32-server.txt)

Edit: seems to have something to do with the mod DimentionalThreading.

**Comment by paulevsGitch** [comment] 2022-08-13 07:31
Yes, looks like the problem is located here:
> at wearblackallday.dimthread.DimThread.swapThreadsAndRun(DimThread.java:34)

I'm not sure what cause it, probably this is external bug not related to ER

**Comment by paulevsGitch** [comment] 2022-08-22 13:32
Looks like this is external issue, so I'm closing it

**Closed by paulevsGitch** 2022-08-22 13:32 UTC
Labels: compatibility, external
